services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $env: "%kernel.environment%"
      $message: '%pw.conversation.entity_message%'
      $projectDir: '%kernel.project_dir%'
      $messageEntity: '%pw.conversation.entity_message%'
  # --------
  # ContactBundle
  # --------

  Pushword\Conversation\PushwordConversation: ~

  Pushword\Conversation\:
    resource: '../../../src/*'
    exclude: '../../../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php,Installer/install.php}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  Pushword\Conversation\Controller\:
    resource: '../../../src/Controller'
    tags: ['controller.service_arguments']

  pushword.admin.conversation:
    class: Pushword\Conversation\Admin\ConversationAdmin
    arguments:
      - ~
      - '%pw.conversation.entity_message%'
      - ~
    tags:
      - {
          name: sonata.admin,
          manager_type: orm,
          label: admin.label.conversation,
        }
    public: true

  pushword.conversation.notifier:
    class: Pushword\Conversation\Service\NewMessageMailNotifier
    tags:
      - { name: doctrine.orm.entity_listener, entity: "%pw.conversation.entity_message%", event: postPersist }

  pushword.conversation.notification_command:
    arguments:
      - '@pushword.conversation.notifier'
    class: Pushword\Conversation\Command\NotificationCommand
    tags: ['console.command']

  # pushword.conversation.twig_extension:
  #   class: Pushword\Conversation\Twig\AppExtension
  #   tags:
  #     - 'twig.extension'
  #     #- { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

  Pushword\Conversation\Repository\MessageRepository:
    arguments: ['@doctrine', '%pw.conversation.entity_message%']
    tags:
      - { name: doctrine.repository_service }
